name: Create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]

        python-version: [ 3.11 ]
        node-version: [ 18.16.0 ]

        solc-version: [ 0.8.19 ]
        ganache-version: [ 7.8.0 ]

        numpy-version: [ 1.24.3 ]
        matplotlib-version: [ 3.7.1 ]
        web3-version: [ 6.2.0 ]
        requests-version: [ 2.28.2 ]

        opt-flags: [ "--optimize --optimize-runs 200" ]

    name: A job to create a release
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Installing Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installing NPM packages
      run: |
        npm install -g solc@${{ matrix.solc-version }}
        npm install -g ganache@${{ matrix.ganache-version }}

    - name: Installing Python packages
      run: |
        python3 -m pip install web3==${{ matrix.web3-version }}
        python3 -m pip install numpy==${{ matrix.numpy-version }}
        python3 -m pip install matplotlib==${{ matrix.matplotlib-version }}
        python3 -m pip install requests==${{ matrix.requests-version }}

    - name: Compiling contracts for PubSub/EventManager.sol
      run: |
        solcjs  ${{ matrix.opt-flags }} --bin --include-path node_modules/ --base-path . --output-dir ./build/ ./PubSub/EventManager.sol
        solcjs  ${{ matrix.opt-flags }} --abi --include-path node_modules/ --base-path . --output-dir ./build/ ./PubSub/EventManager.sol
        mv ./build/PubSub_EventManager_sol_EventManager.bin   ./build/EventManager.bin
        mv ./build/PubSub_EventManager_sol_EventManager.abi   ./build/EventManager.abi

    - name: Compiling contracts for PubSub/PubSubService.sol
      run: |
        solcjs  ${{ matrix.opt-flags }} --bin --include-path node_modules/ --base-path . --output-dir ./build/ ./PubSub/PubSubService.sol
        solcjs  ${{ matrix.opt-flags }} --abi --include-path node_modules/ --base-path . --output-dir ./build/ ./PubSub/PubSubService.sol
        mv ./build/PubSub_PubSubService_sol_PubSubService.bin ./build/PubSubService.bin
        mv ./build/PubSub_PubSubService_sol_PubSubService.abi ./build/PubSubService.abi

    - name: Compiling contracts for tests/HelloWorldSubscriber.sol
      run: |
        solcjs  ${{ matrix.opt-flags }} --bin --include-path node_modules/ --base-path . --output-dir ./build/ ./tests/HelloWorldSubscriber.sol
        solcjs  ${{ matrix.opt-flags }} --abi --include-path node_modules/ --base-path . --output-dir ./build/ ./tests/HelloWorldSubscriber.sol
        mv ./build/tests_HelloWorldSubscriber_sol_HelloWorldSubscriber.bin ./build/HelloWorldSubscriber.bin
        mv ./build/tests_HelloWorldSubscriber_sol_HelloWorldSubscriber.abi ./build/HelloWorldSubscriber.abi

    - name: Compiling contracts for tests/HelloWorldPublisher.sol
      run: |
        solcjs  ${{ matrix.opt-flags }} --bin --include-path node_modules/ --base-path . --output-dir ./build/ ./tests/HelloWorldPublisher.sol
        solcjs  ${{ matrix.opt-flags }} --abi --include-path node_modules/ --base-path . --output-dir ./build/ ./tests/HelloWorldPublisher.sol
        mv ./build/tests_HelloWorldPublisher_sol_HelloWorldPublisher.bin   ./build/HelloWorldPublisher.bin
        mv ./build/tests_HelloWorldPublisher_sol_HelloWorldPublisher.abi   ./build/HelloWorldPublisher.abi

    - name: Calculating checksums of the binary
      run: |
        sha256sum ./build/EventManager.bin  >> ./build/checksums.txt
        sha256sum ./build/EventManager.abi  >> ./build/checksums.txt
        sha256sum ./build/PubSubService.bin >> ./build/checksums.txt
        sha256sum ./build/PubSubService.abi >> ./build/checksums.txt
        sha256sum ./build/HelloWorldPublisher.bin  >> ./build/checksums.txt
        sha256sum ./build/HelloWorldPublisher.abi  >> ./build/checksums.txt
        sha256sum ./build/HelloWorldSubscriber.bin >> ./build/checksums.txt
        sha256sum ./build/HelloWorldSubscriber.abi >> ./build/checksums.txt

    - name: Prepare binaries for gas cost evaluation
      run: |
        mkdir -p ./build/PubSub
        cp ./build/EventManager.bin  ./build/PubSub/EventManager.bin
        cp ./build/EventManager.abi  ./build/PubSub/EventManager.abi
        cp ./build/PubSubService.bin ./build/PubSub/PubSubService.bin
        cp ./build/PubSubService.abi ./build/PubSub/PubSubService.abi
        mkdir -p ./build/tests
        cp ./build/HelloWorldPublisher.bin  ./build/tests/HelloWorldPublisher.bin
        cp ./build/HelloWorldPublisher.abi  ./build/tests/HelloWorldPublisher.abi
        cp ./build/HelloWorldSubscriber.bin ./build/tests/HelloWorldSubscriber.bin
        cp ./build/HelloWorldSubscriber.abi ./build/tests/HelloWorldSubscriber.abi

    - name: Run publish gas cost evaluation
      run: |
        python3 ./tests/MultiSubsGasCostEval.py

    - name: Run subscribe gas cost evaluation
      run: |
        python3 ./tests/MultiPubsGasCostEval.py

    - name: Store evaluation figures to assets branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 ./utils/GitHubCreateFile.py --path "assets/${{ github.ref_name }}-publish_gas_cost.svg"   --commit-msg "Uploaded file assets/${{ github.ref_name }}-publish_gas_cost.svg"   --file "${{ github.workspace }}/build/publish_gas_cost.svg"   --branch assets-gas-eval
        python3 ./utils/GitHubCreateFile.py --path "assets/${{ github.ref_name }}-subscribe_gas_cost.svg" --commit-msg "Uploaded file assets/${{ github.ref_name }}-subscribe_gas_cost.svg" --file "${{ github.workspace }}/build/subscribe_gas_cost.svg" --branch assets-gas-eval

    - name: Generate release note
      run: |
        echo "# Release note"                   >> ./build/release_note.md
        echo "## Contracts"                     >> ./build/release_note.md
        echo "- PubSub/EventManager.sol"        >> ./build/release_note.md
        echo "- PubSub/PubSubService.sol"       >> ./build/release_note.md
        echo "- tests/HelloWorldPublisher.sol"  >> ./build/release_note.md
        echo "- tests/HelloWorldSubscriber.sol" >> ./build/release_note.md
        echo "" >> ./build/release_note.md
        echo "## Build configurations"                      >> ./build/release_note.md
        echo "- OS: \`${{ matrix.os }}\`"                   >> ./build/release_note.md
        echo "- Node version: \`$(node --version)\`"        >> ./build/release_note.md
        echo "- Solc version: \`$(solcjs --version)\`"      >> ./build/release_note.md
        echo "- Optimizations: \`${{ matrix.opt-flags }}\`" >> ./build/release_note.md
        echo "" >> ./build/release_note.md
        echo "## Checksums"       >> ./build/release_note.md
        echo "\`\`\`"             >> ./build/release_note.md
        cat ./build/checksums.txt >> ./build/release_note.md
        echo "\`\`\`"             >> ./build/release_note.md
        echo "" >> ./build/release_note.md
        echo "## Gas Cost Evaluations" >> ./build/release_note.md
        echo "### Gas Cost of Publishing Events"         >> ./build/release_note.md
        echo ""                                          >> ./build/release_note.md
        echo '!'"[publish_gas_cost](/../../blob/assets-gas-eval/assets/${{ github.ref_name }}-publish_gas_cost.svg)"     >> ./build/release_note.md
        echo ""                                          >> ./build/release_note.md
        echo "### Gas cost of Subscribing to Publishers" >> ./build/release_note.md
        echo ""                                          >> ./build/release_note.md
        echo '!'"[subscribe_gas_cost](/../../blob/assets-gas-eval/assets/${{ github.ref_name }}-subscribe_gas_cost.svg)" >> ./build/release_note.md
        echo ""                                          >> ./build/release_note.md
        echo "" >> ./build/release_note.md

    - name: Echo release note
      run: |
        cat ${{ github.workspace }}/build/release_note.md

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workspace }}/build/release_note.md
        files: |
          ${{ github.workspace }}/build/EventManager.bin
          ${{ github.workspace }}/build/EventManager.abi
          ${{ github.workspace }}/build/PubSubService.bin
          ${{ github.workspace }}/build/PubSubService.abi
          ${{ github.workspace }}/build/HelloWorldPublisher.bin
          ${{ github.workspace }}/build/HelloWorldPublisher.abi
          ${{ github.workspace }}/build/HelloWorldSubscriber.bin
          ${{ github.workspace }}/build/HelloWorldSubscriber.abi
          ${{ github.workspace }}/build/publish_gas_cost.svg
          ${{ github.workspace }}/build/subscribe_gas_cost.svg
