name: Running Solidity Unit Tests for PubSub contracts


on:
  push:
    branches: [ main ]
    paths:
      - 'PubSub/**'
      - 'tests/PubSub/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'PubSub/**'
      - 'tests/PubSub/**'


jobs:
  run_sol_contracts_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        solc-version: [ 0.8.21 ]
        chain-fork: [ shanghai ]
        opt-runs: [ 200 ]

    name: A job to run solidity unit tests on github actions CI
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Solidity Unit Testing Action
      uses: EthereumRemix/sol-test@v1.1
      with:
        test-path: 'tests/PubSub'
        compiler-version: ${{ matrix.solc-version }}
        optimize: true
        optimizer-runs: ${{ matrix.opt-runs }}
        hard-fork: ${{ matrix.chain-fork }}
